---
- name: Does the Chrome APT repo exists?
  stat: path={{ chrome_apt_file }}
  register: source_file

- name: Add Google Chrome repo
  copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main"
        dest={{ chrome_apt_file }}
        owner=root group=root mode=644
  when: source_file.stat.exists == false

- shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  when: source_file.stat.exists == false

- name: Install Google Chrome
  apt: update_cache=yes pkg=google-chrome-stable state=installed
