---
- include: chrome.yml tags=chrome
- include: spotify.yml tags=spotify
- include: gnome.yml tags=gnome
- include: i3.yml tags=i3

- name: Install restricted extras
  apt: update_cache=yes package=ubuntu-restricted-extras state=present
