---
- include: chrome.yml tags=chrome
- include: spotify.yml tags=spotify

- name: Install Gnome & i3
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - gnome-shell
    - i3

- name: Link configurations
  file: src=~/.dot/{{ item }} dest=~/.{{ item }} state=link
  with_items:
    - i3
