- name: Install APT packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - ack-grep
    - curl
    - docker.io
    - git
    - mercurial
    - python-pip
    - python2.7
    - tmux
    - vim
    - zsh
